name: build and test
description: Builds and Tests the application

runs:
  using: composite
  steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Install
      uses: ./.github/actions/install

    - name: Build
      run: pnpm build
      shell: bash

    - name: Typecheck
      run: pnpm typecheck
      shell: bash

    - name: Test
      run: pnpm test
      shell: bash
