name: Pull request with automerge dependabot
on: pull_request

permissions:
    contents: write
    pull-requests: write

jobs:
    quality-check:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v4
            - uses: ./.github/actions/build-test
              name: Build & Test
    dependabot:
        runs-on: ubuntu-latest
        needs: quality-check
        if: github.event.pull_request.user.login == 'dependabot[bot]' && github.repository == 'kirkrd/portfolio'
        steps:
            - name: Dependabot metadata
              id: metadata
              uses: dependabot/fetch-metadata@v2
              with:
                  github-token: '${{ secrets.GITHUB_TOKEN }}'
            - name: Enable auto-rebase for Dependabot PRs
              run: gh pr rebase --auto  "$PR_URL"
              env:
                  PR_URL: ${{github.event.pull_request.html_url}}
                  GH_TOKEN: ${{secrets.GITHUB_TOKEN}}
            - name: Approve the PR
              run: gh pr review --approve "$PR_URL"
              env:
                  PR_URL: ${{github.event.pull_request.html_url}}
                  GH_TOKEN: ${{secrets.GITHUB_TOKEN}}
